---
- name: Provision instance(s)
  amazon.aws.ec2_instance:
    key_name: "{{ key_name }}"
    name: "{{ id }}"
    security_group: "{{ result_sec_group.group_id }}"
    image_id: "{{ image }}"
    instance_type: m4.large
    vpc_subnet_id: "{{ vpc_subnet.subnets[0].subnet_id }}"
    region: "{{ region }}"
    count: 1
    network:
      assign_public_ip: yes
      delete_on_termination: yes
    detailed_monitoring: no
    ebs_optimized: no
    tags:
      Name: "{{ id }}-ec2-{{ env }}"
      env: "{{ env }}"
