---
- name: Create VPC
  register: vpc
  amazon.aws.ec2_vpc_net:
    name: "{{ id }}-vpc"
    cidr_block: 10.1.0.0/16
    region: "{{ region }}"
    tags:
      Name: "{{ id }}-vpc"
      env: sandbox

- name: Create Internet gateway
  register: igw
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    tags:
      Name: "{{ id }}-igw"
      env: sandbox

- name: Create public route table
  register: gateway_route_table
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    gateway_id: "{{ igw.gateway_id }}"
    tags:
      Name: "{{ id }}-route-table"
      env: sandbox

- name: Create subnet 1
  register: subnet1
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.1.1.0/24
    az: "{{ region }}a"
    tags:
      Name: "{{ id }}-subnet-a"
      env: sandbox
      
- name: Create subnet 2
  register: subnet2
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.1.2.0/24
    az: "{{ region }}b"
    tags:
      Name: "{{ id }}-subnet-b"
      env: sandbox
      
- name: Create subnet 3
  register: subnet3
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.1.3.0/24
    az: "{{ region }}c"
    tags:
      Name: "{{ id }}-subnet-c"
      env: sandbox
      
- name: Fetch VPC subnets
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ region }}"
  register: vpc_subnets

- name: Collect VPC subnets
  loop: "{{ vpc_subnets.subnets }}"
  ansible.builtin.set_fact:  
    vpc_subnet_list: "{{ vpc_subnet_list }} + [ '{{ item.subnet_id }}' ]"
  
- name: Add route table
  register: public_route_table
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    tags: 
      Name: public
    subnets:
      - "{{ subnet1.subnet.id }}"
      - "{{ subnet2.subnet.id }}"
      - "{{ subnet3.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
      - dest: ::/0
        gateway_id: "{{ igw.gateway_id }}"
