---
- name: Create VPC
  register: vpc
  amazon.aws.ec2_vpc_net:
    name: "{{ id }}-vpc"
    cidr_block: 10.1.0.0/16
    region: "{{ region }}"
    tags:
      Name: "{{ id }}-vpc"
      env: sandbox
