---
# tasks file for aws-get-vpc-info
- name: Get VPC Info
  register: aws_vpc
  amazon.aws.ec2_vpc_net_info:
    region: "{{ aws_region }}"
  #  filters:
  #    "tag:Name": Example

- name: Collect VPC ID
  ansible.builtin.set_fact:
    aws_vpc_id: "{{ aws_vpc.vpcs[0].vpc_id }}"

- name: Fetch VPC Subnets
  register: aws_vpc_subnet
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ aws_region }}"

- name: Collect VPC Subnets
  loop: "{{ aws_vpc_subnet.subnets }}"
  ansible.builtin.set_fact:  
    vpc_subnet_list: "{{ vpc_subnet_list }} + [ '{{ item.subnet_id }}' ]"
