---
- name: Create ssh keypair to AWS
  register: ssh_key
  amazon.aws.ec2_key:
    name: "{{ aws_keypair }}"
    region: "{{ region }}"

- name: Set private key fact
  ansible.builtin.set_fact:
    priv_key: "{{ ssh_key.key.private_key }}"
  
- name: Copy ssh private key
  ansible.builtin.copy:
    content: "{{ priv_key }}"
    dest: /tmp/ansible-runner.pem
    mode: '0400'
