---
- name: Create ssh keypair to AWS
  register: ssh_key
  amazon.aws.ec2_key:
    name: "{{ keypair }}"
    region: "{{ region }}"

- name: Copy ssh private key
  ansible.builtin.copy:
    content: "{{ ssh_key.private_key }}"
    dest: /tmp/ansible-runner.pem
    mode: '0400'
