---

- name: AWS playbook
  hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - amazon.aws

  vars:
    key_name: runner
    region: us-east-2
    image: ami-078cbc4c2d057c244 # RHEL9 image for us-east-2 x86_64
    id: "control-node"
    sec_group: "{{ id }}-sec"

  tasks:

    - name: Facts
      tags: always
      block:
      - name: Get instances facts
        register: result
        amazon.aws.ec2_instance_info:
          region: "{{ region }}"

      - name: Instances ID
        loop: "{{ result.instances }}"
        debug:
          msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"

    - name: Provisioning EC2 instances
      tags: ['never', 'create_ec2']
      block:
      - name: Create VPC
        register: vpc
        amazon.aws.ec2_vpc_net:
          name: "{{ id }}-vpc"
          cicr_block: 10.1.0.0/16
          region: "{{ region }}"
          tags:
            env: sandbox
            
      - name: Set VPC ID fact
        ansible.builtin.set_fact:
          vpc_id: "{{ vpc.vpc.id }}"
          
      - name: Create Internet gateway
        register: igw
        amazon.aws.ec2_vpc_igw:
          vpc_id: "{{ vpc_id }}"
          state: present
          tags:
            env: sandbox
            
      - name: Create public route table
        register: gateway_route_table
        amazon.aws.ec2_vpc_route_table:
          vpc_id: "{{ vpc_id }}"
          region: "{{ region }}"
          gateway_id: "{{ igw.gateway_id }}"
          tags:
            name: "{{ id }}-route-table"
            env: sandbox
          
      - name: Create subnet 
        register: subnet
        amazon.aws.ec2_vpc_subnet:
          state: present
          vpc_id: "{{ vpc_id }}"
          cidr: 10.1.0.0/24
          tags:
            name: "{{ id }}-subnet"
            env: sandbox
      
      - name: Add route table
        register: public_route_table
        amazon.aws.ec2_vpc_route_table:
          vpc_id: "{{ vpc_id }}"
          region: "{{ region }}"
          tags: 
            name: public
          subnets:
            - "{{ subnet.subnet.id }}"'
          routes:
            - dest: 0.0.0.0/0
              gateway_id: "{{ igw.gateway_id }}"
            - dest: ::/0
              gateway_id: "{{ igw.gateway_id }}"
            
      - name: Upload public key to AWS
        amazon.aws.ec2_key:
          name: "{{ key_name }}"
          key_material: "{{ lookup('file', '~/.ssh/{{ key_name }}.pub') }}"
          region: "{{ region }}"

      - name: Create security group
        register: result_sec_group
        amazon.aws.ec2_group:
          name: "{{ sec_group }}"
          description: "Sec group for app {{ id }}"
          vpc_id: "{{ vpc_id }}"
          region: "{{ region }}"
          rules:
            - proto: tcp
              ports:
                - 22
              cidr_ip: 0.0.0.0/0
              rule_desc: allow all on ssh port
          tags:
            env: sandbox
        
      - name: Provision instance(s)
        amazon.aws.ec2_instance:
          key_name: "{{ key_name }}"
          name: "{{ id }}"
          security_group: "{{ result_sec_group.group_id }}"
          image: "{{ image }}"
          instance_type: t2.micro
          vpc_subnet_id: "{{ subnet.subnet.id }}"
          region: "{{ region }}"
          count: 1
          tags:
            env: sandbox

