---

- name: AWS playbook
  hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - amazon.aws

  vars:
    key_name: runner
    region: us-east-2
    image: ami-078cbc4c2d057c244 # RHEL9 image for us-east-2 x86_64
    id: "control-node"
    sec_group: "{{ id }}-sec"

  tasks:

    - name: Facts
      tags: always
      block:
      - name: Get instances facts
        register: result
        amazon.aws.ec2_instance_info:
          region: "{{ region }}"

      - name: Instances ID
        loop: "{{ result.instances }}"
        debug:
          msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"

    - name: Provisioning EC2 instances
      tags: ['never', 'create_ec2']
      block:
      - name: Upload public key to AWS
        amazon.aws.ec2_key:
          name: "{{ key_name }}"
          key_material: "{{ lookup('file', '~/.ssh/{{ key_name }}.pub') }}"
          region: "{{ region }}"

      - name: Create security group
        register: result_sec_group
        amazon.aws.ec2_group:
          name: "{{ sec_group }}"
          description: "Sec group for app {{ id }}"
          #vpc_id: 12345
          region: "{{ region }}"
          rules:
            - proto: tcp
              ports:
                - 22
              cidr_ip: 0.0.0.0/0
              rule_desc: allow all on ssh port
          tags:
            env: sandbox
        
      - name: Provision instance(s)
        amazon.aws.ec2_instance:
          key_name: "{{ key_name }}"
          name: "{{ id }}"
          security_group: "{{ result_sec_group.group_id }}"
          image: "{{ image }}"
          instance_type: t2.micro
          region: "{{ region }}"
          count: 1
          tags:
            env: sandbox

