name: AWS CLI
on:
  push:
    branches:
      - 'main'
    paths:
      - 'trigger.md'
  workflow_dispatch:

jobs:
  Setup:
    name: Setup Ubuntu runner
    runs-on: ubuntu-18.04
    steps:        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        
    - name: Manual stuffs
      run: |
        export VPCID=`aws ec2 describe-vpcs --filter Name=state,Values=available  --query Vpcs[].VpcId --output text`
        aws ec2 describe-subnets --filters Name=vpc-id,Values=$VPCID
